### ISSUE TITLE
JIFifier Functionality 

### ISSUE THREAD

**Issue by AbsentQuarter** [AuriRex/DiscordBot#2]
Hi, we really require this must-have feature. It would vastly improve our meme deployment pipeline and remove numerous inefficiencies. 
**We are in need of a feature that switches every first g in a word with a j in a given string.**
While we could submit a pull request, we respect the expertise of the maintaining dev and will humbly wait for you to implement the feature. 
_Also, if that can be done by week-end that would be great. Thanks!_

**Comment by AuriRex** [comment]
afa3923643f9290188d6a889715f6165765da704 and 6b5fdb28183b7c34a789a42cdfd8168849f48dc3 should have addressed this very important issue.
Please make sure to *not* look at the commits linked above and/or the code associated with those commits as it's 😩 and 🥶.

Here's a little gift for reading this far:
![image](https://user-images.githubusercontent.com/37329066/158905109-9bfb0114-52f8-453c-93e4-08b42a48399a.png)
